### ISSUE TITLE
Test the current code (8)

### ISSUE THREAD

**Issue by joerischasfoort** [LCfP/Agent-Based-Stock-Market-Model#13]
Test all current model code

**Comment by joerischasfoort** [comment]
# Splitting the work 

##Joeri:
database.py
marketmechanims.py
setup.py
randomset.py

##Julian
agents.py
firms.py
functions.py
stocks.py

**Comment by joerischasfoort** [comment]
I had a problem with pytest. Just couldn't get it to work with a fixtures. Found out my Pycharm was running nosetest by default. 

You can change that by --> File | Settings | Tools | Python Integrated Tools and change the default test runner to py.test. Then you'll get the py.test option to create tests instead of the unittest one.

**Comment by ZireJP** [comment]
wrote tests for agents, firms and functions that are not print functions. stocks has just the initialization.

**Comment by N-Wouda** [comment]
Put on backlog.

**Comment by N-Wouda** [comment]
Re-opening since @ZireJP will be working on this for the upcoming sprint.
