### ISSUE TITLE
Update current notebook (3h)

### ISSUE THREAD

**Issue by N-Wouda** [LCfP/Agent-Based-Stock-Market-Model#26]
Dependency on #25

**Comment by joerischasfoort** [comment]
The current notebook can now provide all non-trader-type information. 

![pricesanddividends](https://cloud.githubusercontent.com/assets/8150061/25906938/4e653548-35a6-11e7-8f17-b7f0bc608ed9.png)
![tradevolumes](https://cloud.githubusercontent.com/assets/8150061/25906939/4e69c72a-35a6-11e7-8c74-4cde40e94a18.png)

**Comment by joerischasfoort** [comment]
Basically, there is trading going on. Prices track fundamentals (dividends) somewhat. The main problem is that there is not enough trading. We need to think about how to solve that.
