### ISSUE TITLE
BUG: 100% chartists crashes the model (1)

### ISSUE THREAD

**Issue by N-Wouda** [LCfP/Agent-Based-Stock-Market-Model#35]

**Comment by ZireJP** [comment]
I cannot reproduce the bug.
On my machine, if there are only chartist there are 0 trades (working as intended how the code is implement currently), but the code doesn't crash.

If it crashes for you, can you give me some explicit parameters where it crashes?

**Comment by N-Wouda** [comment]
@ZireJP @joerischasfoort @ChristopherStockermans could you confirm this is not a problem any longer? If it persists, could you give a detailed description on how to reproduce this behaviour?

**Comment by joerischasfoort** [comment]
We now have an initial price, so this is no longer a problem.
