### ISSUE TITLE
Market matching mechanism

### ISSUE THREAD

**Issue by joerischasfoort** [LCfP/Agent-Based-Stock-Market-Model#8]
We added a market matching mechanism function which had as input an agentSet and wanted its output to be a list of matched agents. Then in the simulation.py we could let these agents have a transaction. However, we now feel that this might lead to a very weird market. Because suppliers can only serve demanding agents once or too often. We also do not take agent inventory of stocks into account. 

Therefore, we are now leaning toward a new type of function with input agentset and output an agentSet after matching **AND TRADING**. Mainly because matching depends on trading. 

*Work in progress.*

**Comment by markkvdb** [comment]
I think this issue is solved today.
